### PR TITLE
fix a bug where the backoff algorithm panics after too many attempts

### PR DESCRIPTION
**Pull request by tadhunt**
because of a bug in the backoff calculation resulting in a negative number being passed to rand.Int63n()

### CODE REVIEW

**Comment by flowchartsman** [comment]
Issue: #4

**Comment by flowchartsman** [comment]
Thanks for the report and the PR! This definitely needs fixing --as you say, the user should be able to pass in whatever they like-- but I have a few issues:

- I think the comments would be better left in the issue report or on the PR itself, rather than cluttering up the source code
- The addition of a `.gitignore` isn't germane to the issue the PR is intended to address, and should be excluded
- I think I would prefer to fix this similarly to how it's done in the aws-sdk-go, [here](https://github.com/aws/aws-sdk-go/blob/v1.35.34/aws/client/default_retryer.go#L78-L123), which was the inspiration for picking this algorithm, IIRC
- your test contains `log.Println` which shouldn't appear in tests
- if your test is a remedial test for a panic condition, it should test that a panic does _not_ occur by using `recover` to prevent the panic and then simply fail the test.
- I would prefer it if the test followed the behavioral naming convention that I used, where the name of the testing function describes the behavior it is testing. This way, when there's a failure or regression, you have something really meaningful to go off of immediately

That said, I think it would probably be better to test the problematic code directly by calling `getnextBackoff` directly from the testing code and asserting that it tops out at `maxDelay` and doesn't panic.  I would also name the test something like `TestRetriesAreCapped`

Let me know if you'd like to take a crack at it, otherwise, I will be sure to address the issue and publish a fix. This thing needs a `go.mod` anyway :D

**Comment by tadhunt** [comment]
All good points. Most are easy, and I can and have taken care of (see updated PR), but because of bullet 3 in your comment above, I need your advice.

Reworking the algorithm to match the AWS SDK is a fundamentally much bigger change with deeper implication because the backoff algorithm is quite a bit different.  In particular it has not only initialDelay, but also minDelay, which this library doesn't currently have.  Further, this library cannot currently return backoff values larger than maxDelay, but the AWS SDK algorithm can and does (actually up to maxDelay+initialDelay).  If I make the assumption that minDelay == initialDelay, then due to the previous comment,  some of the test cases fail because existing invariants no longer hold true.

So the question is:  How should I proceed?  I implemented the AWS SDK algorithm in the updated PR, and changed the invariants in the test cases that broke as a consequence.  This code assumes minDelay == initialDelay, so it doesn't otherwise change the API.

**Comment by flowchartsman** [comment]
Let me take a look and get back to you after the holiday. If anything, it was an aversion to just continually underflowing and rechecking `backoff`. There should be a better way, IMHO, since conceivably it will then roll right back around to zero (even if, admittedly, it takes awhile)

**Comment by tadhunt** [comment]
Cool.  Re: the underflowing, Yeah, what I liked about the code you pointed me at as reference is that it computes the number of attempts at which overflow happens, and doesn't bother going beyond it.  Happy holidays!

**Review by flowchartsman — APPROVED** [review]
LGTM

**Comment by flowchartsman** [comment]
Merged, thanks!

**Pull request merged**
